backend:
  name: git-gateway
  branch: main

media_folder: images

collections:
  - name: news
    label: News & Articles
    folder: _posts
    create: true
    fields:
      - {label: Title, name: title, widget: string}
      - {label: Date, name: date, widget: datetime}
      - {label: Photo, name: photo, widget: image, required: false}
      - {label: Body, name: body, widget: markdown}
